DATASET:
  root_dataset: "../data/streethazards/test"
  list_train: "../data/streethazards/train/train.odgt"
  list_val: "../data/streethazards/test/test.odgt"
  num_class: 13
  imgSizes: (300, 375, 450, 525, 600)
  imgMaxSize: 1000
  padding_constant: 8
  segm_downsampling_rate: 8
  random_flip: True

MODEL:
  arch_encoder: "resnet50dilated"
  arch_decoder: "ppm_deepsup_embedding"
  fc_dim: 2048

TRAIN:
  batch_size_per_gpu: 2
  num_epoch: 20
  start_epoch: 0
  epoch_iters: 5000
  optim: "SGD"
  lr_encoder: 0.02
  lr_decoder: 0.02
  lr_pow: 0.9
  beta1: 0.9
  weight_decay: 1e-4
  deep_sup_scale: 0.4
  fix_bn: False
  workers: 16
  disp_iter: 20
  seed: 304

VAL:
  visualize: False
  checkpoint: "epoch_20.pth"

TEST:
  checkpoint: "epoch_20.pth"
  result: "./"

DIR: "./ckpt"
